### ISSUE TITLE
Cannot deploy 

### ISSUE THREAD

**Issue by jayb967** [oddbit/tanam#226]
**Describe the bug**
Document definitions conflict between tanam and @google-cloud node_modules

**To Reproduce**
1. Cloned starter project
2. Changed necessary files
3. npm i
3. ran npm run build && npm run deploy, also tried firebase deploy --token <myCopiedToken> 

**Expected behavior**
Deploy function(s)

**Additional context**
- On ubuntu running node 8.10
- Locally using nvm w version 8.13 after a firebase error.
Here are the error/s I am getting both on ubuntu 18.04, same errors locally

```ubuntu@ip-<myIP>:~/tanam-starter/functions$ firebase deploy --token <myCopiedToken>

=== Deploying to '<myProjectID>'...

i  deploying database, storage, firestore, functions, hosting
Running command: npm --prefix functions run lint

> functions@ lint /home/ubuntu/tanam-starter/functions
> tslint --project tsconfig.json

no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
Running command: npm --prefix functions run build

> functions@ build /home/ubuntu/tanam-starter/functions
> tsc

node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/tanam/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/tanam/node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1 - error TS6200: Definitions of the following identifiers conflict with those in another file: DocumentData, UpdateData, Firestore, GeoPoint, Transaction, WriteBatch, WriteResult, DocumentReference, DocumentSnapshot, QueryDocumentSnapshot, OrderByDirection, WhereFilterOp, Query, QuerySnapshot, DocumentChangeType, CollectionReference, FieldValue, FieldPath, Timestamp, v1beta1, v1, FirebaseFirestore

23 declare namespace FirebaseFirestore {
   ~~~~~~~

  node_modules/@google-cloud/firestore/types/firestore.d.ts:23:1
    23 declare namespace FirebaseFirestore {
       ~~~~~~~
    Conflicts are in this file.

node_modules/tanam/node_modules/@google-cloud/firestore/types/firestore.d.ts:95:5 - error TS2374: Duplicate string index signature.

95     [key: string]: any; // Accept other properties, such as GRPC settings.

Found 3 errors.


npm ERR! Linux 4.15.0-1032-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "functions" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! functions@ build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the functions@ build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the functions package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs functions
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls functions
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/tanam-starter/npm-debug.log



```

Here is my log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   'functions',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle functions@~prebuild: functions@
6 silly lifecycle functions@~prebuild: no script for prebuild, continuing
7 info lifecycle functions@~build: functions@
8 verbose lifecycle functions@~build: unsafe-perm in lifecycle true
9 verbose lifecycle functions@~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/tanam-starter/functions/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle functions@~build: CWD: /home/ubuntu/tanam-starter/functions
11 silly lifecycle functions@~build: Args: [ '-c', 'tsc' ]
12 silly lifecycle functions@~build: Returned: code: 2  signal: null
13 info lifecycle functions@~build: Failed to exec build script
14 verbose stack Error: functions@ build: `tsc`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid functions@
16 verbose cwd /home/ubuntu/tanam-starter
17 error Linux 4.15.0-1032-aws
18 error argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "functions" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error functions@ build: `tsc`
22 error Exit status 2
23 error Failed at the functions@ build script 'tsc'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the functions package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs functions
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls functions
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by anandaprabawa** [comment]
Hi @jayb967 
The [Tanam Starter Project](https://github.com/oddbit/tanam-starter) has been updated to fix this issue, caused by latest firebase-admin which is version 8.
Please clone new starter project.

Thank you.
